<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dxcbjqlnt/image/upload/v1554338976/quicksquare_2019330144736322_Cropped.jpg" alt="Oluwaloni Richard">
                        <h6>Sodeinde Oluwaloni Richard</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Lonnyrichard" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/lonnyrichard27" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@lonnyrichard77" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, my name is Oluwaloni Richard and im a goal-driven aspiring full stack developer  who is highly enthusiastic about technology and with the mindset of leaving an impact for eternity, making positive transitions nationally using technologies and eventually globally.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JAVASCRIPT | BOOTSTRAP4 | HTML5 & CSS3</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
